name: Debt Data
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *' # every two hours

jobs:
  job_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748 # pin@v2
      - name: Install dependencies
        run: yarn install

      - name: Download debt data
        run: yarn download-debt-data

      - name: Upload debt data to S3
        uses: Synthetixio/upload-s3-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: synthetix-staking-dispersed
          source_dir: 'debt-data'
          destination_dir: 'debt-data'