name: Main Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Read package.json
        uses: tyankatsu0105/read-package-version-actions@v1
        id: package-version
      - run: npm run test
      - run: npm run build
      # publish
      - name: Show version number
        run: echo "Publishing version ${{ steps.package-version.outputs.version }}"
      - run: npm version ${{ steps.package-version.outputs.version }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}