name: Main Workflow
on:
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run test

      # publish
      - name: Populate DEV_VERSION
        run: |
          GIT_SHA_FULL="${{ github.sha }}"
          GIT_SHA="${GIT_SHA_FULL:0:8}"
          if [ "${{ github.run_attempt }}" == "1" ]; then
            export DEV_VERSION="0.0.0-$GIT_SHA"
          else
            export DEV_VERSION="0.0.0-$GIT_SHA.${{ github.run_attempt }}"
          fi
          echo "DEV_VERSION=$DEV_VERSION" >> $GITHUB_ENV
          echo "DEV_VERSION=$DEV_VERSION"

      - run: npm --workspaces version "$DEV_VERSION"
      - run: npm --workspaces publish --tag dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
