name: Main Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - name: Read package.json
        uses: tyankatsu0105/read-package-version-actions@v1
        id: package-version
      - run: npm ci
      - run: npm run build
      - run: npm run test
      # publish
      - name: Show version number
        run: echo "Publishing version ${{ steps.package-version.outputs.version }}"
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: $NPM_TOKEN
          check-version: true
        
