name: Publish Library

on:
  workflow_dispatch:
    inputs:
      synthetix_version:
        description: 'Upstream `synthetix` repo version (leave empty if no update)'
        required: false
      monorepo_version:
        description: 'New Monorepo Version (ex. 2.50.0-alpha) (leave empty to "patch")'
        required: false

jobs:
  update_version:
    name: Update synthetix in contracts-interface
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - run: yarn npm whoami
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: yarn install --immutable

      - name: Config git identity
        run: |
          git config --global user.email "ci@cc.snxdao.io"
          git config --global user.name "Synthetix CI"

      - name: Resolve version
        run: |
          if [ -n "${{ github.event.inputs.monorepo_version }}" ]; then
            export VERSION_CANDIDATE="${{ github.event.inputs.monorepo_version }}"
          else
            export VERSION_CANDIDATE="patch"
          fi
          git reset --hard
          yarn version "$VERSION_CANDIDATE"
          export NEW_VERSION="$(jq -r .version < package.json)"
          echo "NEW_VERSION=$NEW_VERSION" 
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          git reset --hard

      - name: Update to the new synthetix version (if present)
        if: github.event.inputs.synthetix_version
        run: |
          yarn up synthetix@${{ github.event.inputs.synthetix_version }}
          git commit -am "synthetix@${{ github.event.inputs.synthetix_version }}" --allow-empty --no-verify

      - run: yarn lint
      - run: yarn build
      - run: yarn test

      - run: yarn workspaces foreach version --deferred ${{ env.NEW_VERSION }}
      - run: yarn version apply --all

      - name: Create git tag and commit changes
        run: |
          git commit -am "v${{ env.NEW_VERSION }}" --allow-empty --no-verify
          git tag -a "v${{ env.NEW_VERSION }}" -m "v${{ env.NEW_VERSION }}"

      - name: Publish packages
        run: yarn workspaces foreach --no-private npm publish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push changes
        run: |
          git push
          git push origin "refs/tags/v${{ env.NEW_VERSION }}"

      - name: Notify dApps
        run: |
          curl -H "Authorization: token ${{ secrets.GH_TOKEN_DAPPS }}" --request POST --data "{\"ref\": \"dev\", \"inputs\": {\"monorepo_version\": \"${{ env.NEW_VERSION }}\"}}" https://api.github.com/repos/Synthetixio/staking/actions/workflows/updateDependency.yml/dispatches
          curl -H "Authorization: token ${{ secrets.GH_TOKEN_DAPPS }}" --request POST --data "{\"ref\": \"develop\", \"inputs\": {\"monorepo_version\": \"${{ env.NEW_VERSION }}\"}}" https://api.github.com/repos/Synthetixio/futures-keepers/actions/workflows/updateDependency.yml/dispatches
          curl -H "Authorization: token ${{ secrets.GH_TOKEN_DAPPS }}" --request POST --data "{\"event_type\": \"update-dependency\", \"client_payload\": {\"version\": \"${{ env.NEW_VERSION }}\"}}" https://api.github.com/repos/Kwenta/kwenta/dispatches
          curl -H "Authorization: token ${{ secrets.GH_TOKEN_DAPPS }}" --request POST --data "{\"event_type\": \"update-dependency\", \"client_payload\": {\"version\": \"${{ env.NEW_VERSION }}\"}}" https://api.github.com/repos/Kwenta/kwenta-api/dispatches
